function [conf_matricies, accuracies] = BoVW_10_fold(imds)
%% BOVW_10_FOLD computes the BoVW using 10-fold cross-validation
[n_cat, ~] = size(unique(imds.Labels));

% pre-allocate vector for all the accuracies
accuracies = zeros(1, 10);

% pre-allocate the confusion matricies
conf_matricies = zeros(n_cat, n_cat, 10);

disp('splitting the dataset');
[imds1, imds2, imds3, imds4, imds5, imds6, imds7, imds8, ... 
    imds9, imds10] = splitEachLabel(imds, ... 
    0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 'randomize');

disp('      imds1 for testing, others for training');
imds_train = imageDatastore(cat(1,imds2.Files, imds3.Files, imds4.Files, ...
    imds5.Files, imds6.Files, imds7.Files, imds8.Files, ... 
    imds9.Files, imds10.Files));
imds_train.Labels = cat(1,imds2.Labels, imds3.Labels, imds4.Labels, ...
    imds5.Labels, imds6.Labels, imds7.Labels, imds8.Labels, ... 
    imds9.Labels, imds10.Labels);

[conf_matricies(:,:,1), accuracies(1)] = BoVW(imds_train, imds1);

disp('      imds2 for testing, others for training');
imds_train = imageDatastore(cat(1,imds1.Files, imds3.Files, imds4.Files, ...
    imds5.Files, imds6.Files, imds7.Files, imds8.Files, ... 
    imds9.Files, imds10.Files));
imds_train.Labels = cat(1,imds1.Labels, imds3.Labels, imds4.Labels, ...
    imds5.Labels, imds6.Labels, imds7.Labels, imds8.Labels, ... 
    imds9.Labels, imds10.Labels);

[conf_matricies(:,:,2), accuracies(2)] = BoVW(imds_train, imds2);

disp('      imds3 for testing, others for training');
imds_train = imageDatastore(cat(1,imds1.Files, imds2.Files, imds4.Files, ...
    imds5.Files, imds6.Files, imds7.Files, imds8.Files, ... 
    imds9.Files, imds10.Files));
imds_train.Labels = cat(1,imds1.Labels, imds2.Labels, imds4.Labels, ...
    imds5.Labels, imds6.Labels, imds7.Labels, imds8.Labels, ... 
    imds9.Labels, imds10.Labels);

[conf_matricies(:,:,3), accuracies(3)] = BoVW(imds_train, imds3);

disp('      imds4 for testing, others for training');
imds_train = imageDatastore(cat(1,imds1.Files, imds2.Files, imds3.Files, ...
    imds5.Files, imds6.Files, imds7.Files, imds8.Files, ... 
    imds9.Files, imds10.Files));
imds_train.Labels = cat(1,imds1.Labels, imds2.Labels, imds3.Labels, ...
    imds5.Labels, imds6.Labels, imds7.Labels, imds8.Labels, ... 
    imds9.Labels, imds10.Labels);

[conf_matricies(:,:,4), accuracies(4)] = BoVW(imds_train, imds4);

disp('      imds5 for testing, others for training');
imds_train = imageDatastore(cat(1,imds1.Files, imds2.Files, imds3.Files, ...
    imds4.Files, imds6.Files, imds7.Files, imds8.Files, ... 
    imds9.Files, imds10.Files));
imds_train.Labels = cat(1,imds1.Labels, imds2.Labels, imds3.Labels, ...
    imds4.Labels, imds6.Labels, imds7.Labels, imds8.Labels, ... 
    imds9.Labels, imds10.Labels);

[conf_matricies(:,:,5), accuracies(5)] = BoVW(imds_train, imds5);

disp('      imds6 for testing, others for training');
imds_train = imageDatastore(cat(1,imds1.Files, imds2.Files, imds3.Files, ...
    imds4.Files, imds5.Files, imds7.Files, imds8.Files, ... 
    imds9.Files, imds10.Files));
imds_train.Labels = cat(1,imds1.Labels, imds2.Labels, imds3.Labels, ...
    imds4.Labels, imds5.Labels, imds7.Labels, imds8.Labels, ... 
    imds9.Labels, imds10.Labels);

[conf_matricies(:,:,6), accuracies(6)] = BoVW(imds_train, imds6);

disp('      imds7 for testing, others for training');
imds_train = imageDatastore(cat(1,imds1.Files, imds2.Files, imds3.Files, ...
    imds4.Files, imds5.Files, imds6.Files, imds8.Files, ... 
    imds9.Files, imds10.Files));
imds_train.Labels = cat(1,imds1.Labels, imds2.Labels, imds3.Labels, ...
    imds4.Labels, imds5.Labels, imds6.Labels, imds8.Labels, ... 
    imds9.Labels, imds10.Labels);

[conf_matricies(:,:,7), accuracies(7)] = BoVW(imds_train, imds7);

disp('      imds8 for testing, others for training');
imds_train = imageDatastore(cat(1,imds1.Files, imds2.Files, imds3.Files, ...
    imds4.Files, imds5.Files, imds6.Files, imds7.Files, ... 
    imds9.Files, imds10.Files));
imds_train.Labels = cat(1,imds1.Labels, imds2.Labels, imds3.Labels, ...
    imds4.Labels, imds5.Labels, imds6.Labels, imds7.Labels, ... 
    imds9.Labels, imds10.Labels);

[conf_matricies(:,:,8), accuracies(8)] = BoVW(imds_train, imds8);

disp('      imds9 for testing, others for training');
imds_train = imageDatastore(cat(1,imds1.Files, imds2.Files, imds3.Files, ...
    imds4.Files, imds5.Files, imds6.Files, imds7.Files, ... 
    imds8.Files, imds10.Files));
imds_train.Labels = cat(1,imds1.Labels, imds2.Labels, imds3.Labels, ...
    imds4.Labels, imds5.Labels, imds6.Labels, imds7.Labels, ... 
    imds8.Labels, imds10.Labels);

[conf_matricies(:,:,9), accuracies(9)] = BoVW(imds_train, imds9);

disp('      imds10 for testing, others for training');
imds_train = imageDatastore(cat(1,imds1.Files, imds2.Files, imds3.Files, ...
    imds4.Files, imds5.Files, imds6.Files, imds7.Files, ... 
    imds8.Files, imds9.Files));
imds_train.Labels = cat(1,imds1.Labels, imds2.Labels, imds3.Labels, ...
    imds4.Labels, imds5.Labels, imds6.Labels, imds7.Labels, ... 
    imds8.Labels, imds9.Labels);

[conf_matricies(:,:,10), accuracies(10)] = BoVW(imds_train, imds10);

end